name: CI
on: push
jobs: 
  build:
    runs-on: self-hosted   
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Build Docker images 
        run: |
          sudo docker build . --file Dockerfile --tag omaral20/webapp:latest
    
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo  docker login -u "omaral20" --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          sudo docker push omaral20/webapp:latest
      
      - name: Check if container is running
        run: |
          if sudo docker ps -a --format '{{.Names}}' | grep -Eq '^webapp$'; then
            sudo docker stop webapp
          fi

      - name: Remove existing container (if any)
        run: |
          if sudo docker ps -a --format '{{.Names}}' | grep -Eq '^webapp$'; then
            sudo docker rm webapp
          fi

      - name: Pull latest Docker image
        run: sudo docker pull omaral20/webapp:latest

      - name: Run Docker container
        run: sudo docker run -d -p 8083:8082 --name webapp omaral20/webapp:latest
  test:
    needs: build
    runs-on: self-hosted
    steps:
    - name: descargar repostorio
      uses: actions/checkout@v3
    - name: preparar base de datos de prueba
      run: |
        sudo mysql -u root < db/baloncesto.sql
        export DATABASE_HOST="jdbc:mysql://localhost"
        export DATABASE_PORT="3306"
        export DATABASE_NAME="baloncesto"
        export DATABASE_USER="usuario"
        export DATABASE_PASS="clave"
  
    - name: realizar pruebas funcionales
      run: | 
        mvn failsafe:integration-test failsafe:verify


  qa:
    needs: test
    runs-on: self-hosted
    continue-on-error: true
    steps: 
    - name: calidad-codigo
     # run:  |
     #   mvn sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -Dsonar.qualitygate.wait=true -Dsonar.login=admin12 -Dsonar.password=admin12


  deploy:
    needs: qa
    runs-on: ubuntu-latest
    steps:
    - name: despliegue
      run: echo "despliegue"
